[features]
seeds = false
[programs.localnet]
frdm = "FRCFKyUkRdiiZEfZdr4vGYAY9azViyRoAXMBJSyAFyKy"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/krishna-rijal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
